baseURL = "/"
languageCode = "en-us"
title = "Coding in Go with Amelie the Gopher"
theme = "beautifulhugo"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  subtitle = "Writing Go in my Burrow"
  logo = "img/avatar-icon.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "2 Jan 2006"
  commit = false
  rss = true

[Author]
  name = "Amelie the Gopher"
  homepage = "http://ameliethegopher.org"
  website = "http://ameliethegopher.org"
  email = "ameliethegopher@protonmail.com"
  github = "ameliethegopher"
  twitter = "AmelieTheGopher"
  reddit = "ameliethegopher"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 3
